#!/usr/bin/env python3
"""
build.py — Embeds all .md files into pages.js so index.html
           works as a plain file:// with zero server needed.

Run whenever you add or edit a .md file:
    python3 build.py
"""
import json
import os
import datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(ROOT, 'pages.js')

pages = {}
for dirpath, _, filenames in os.walk(ROOT):
    for fname in sorted(filenames):
        if not fname.endswith('.md'):
            continue
        full = os.path.join(dirpath, fname)
        rel  = os.path.relpath(full, ROOT).replace(os.sep, '/')
        if any(part.startswith('.') for part in rel.split('/')):
            continue
        with open(full, encoding='utf-8') as f:
            pages[rel] = f.read()

js  = '// AUTO-GENERATED by build.py — do not edit manually.\n'
js += f'// {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}\n\n'
js += f'const PAGES = {json.dumps(pages, ensure_ascii=False, indent=2)};\n'

with open(OUT, 'w', encoding='utf-8') as f:
    f.write(js)

total = sum(len(v) for v in pages.values())
print(f'✅  pages.js written — {len(pages)} pages, {total // 1024} KB')
print(f'📄  Open index.html directly in your browser')
